openapi: 3.0.1
info:
  description: HTTP server that handle cute Gophers.
  title: gophers-api
  version: 0.1.0
servers:
- url: /
tags:
- description: Handle Gophers
  name: gophers
paths:
  /healthz:
    get:
      operationId: checkHealth
      responses:
        "200":
          content:
            text/plain:
              schema:
                enum:
                - OK
                type: string
          description: OK message.
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /gophers:
    get:
      description: List Gophers
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Gopher'
                type: array
          description: Return the Gophers list.
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
      tags:
      - gophers
  /gopher:
    delete:
      description: Delete a gopher by a given name
      parameters:
      - description: Gopher name
        in: query
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: OK
        "404":
          content: {}
          description: A gopher with the specified Name was not found.
      tags:
      - gophers
    get:
      description: Get a gopher by a given name
      parameters:
      - description: Gopher name
        in: query
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gopher'
          description: A gopher
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "404":
          content: {}
          description: A gopher with the specified Name was not found.
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
      tags:
      - gophers
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_gopher_put_request'
        description: The Gopher to create.
        required: false
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gopher'
          description: Created
        "409":
          content: {}
          description: Gopher already exists
      summary: Add a new Gopher
      tags:
      - gophers
      x-codegen-request-body-name: gopher
    put:
      description: Update a gopher
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_gopher_put_request'
        description: The Gopher to update.
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gopher'
          description: Updated
        "404":
          content: {}
          description: A gopher with the specified Name was not found.
      tags:
      - gophers
      x-codegen-request-body-name: gopher
components:
  schemas:
    Gopher:
      example:
        displayname: My Gopher
        name: my-gopher
        url: https://raw.githubusercontent.com/scraly/gophers/main/arrow-gopher.png
      properties:
        name:
          example: my-gopher
          type: string
        displayname:
          example: My Gopher
          type: string
        url:
          example: https://raw.githubusercontent.com/scraly/gophers/main/arrow-gopher.png
          type: string
      type: object
    _gopher_put_request:
      properties:
        name:
          type: string
        displayname:
          type: string
        url:
          type: string
      required:
      - displayname
      - name
      - url
      type: object
x-original-swagger-version: "2.0"
